### ISSUE TITLE
Visualizar la evolución de las causas de presión

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#11]
Posibilidad de usar para las visualizaciones un timeline de fechas y recursos animado o meramente textual.
Se visualizarán los hitos internos o externos que hayan sido marcados como visualizables en la causa de presión.

Posibilidades:
* https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1TLHLYi0wsENBlUGh4AvUz6cUkwVW8XgUPZ9WWMuqYSo&font=Default&lang=es&initial_zoom=2&height=650
* http://foundation.zurb.com/forum/posts/19277-responsive-timeline-with-foundation
* https://duckduckgo.com/about

**Comment by AnaMariaCM** [comment]
Ante la disyuntiva de si tener listo para finales de enero o bien la visualización de las causas de presión o bien tener activo el tema de las píldoras de contenidos, POletika AG 2/12/2016 dice que primero tengamos la visualización de las causas de presión. Mostremos Poletika como un sistema de medición. Las píldoras que vengan en febrero.

**Comment by pr3ssh** [comment]
@AnaMariaCM Oído! La tercera es como muy sencilla si y se puede navegar por ella de forma fácil. Lo estudiamos con el equipo de diseño y lo vamos comentando por aquí.

**Comment by pr3ssh** [comment]
Cada vesz veo más interesante el tema de usar la tercera opción. Y sí @AnaMariaCM, siempre estaríamos dentro de la causa por lo que puede quedar bien incluso sin imágenes sino solo con un texto y su fecha (que es de lo que se trata) ya que las imágenes y demás irán en el resto de píldoras de contenidos.

@poletika/managers os parece que elijamos ésta o una similar para la visualización?

**Comment by pr3ssh** [comment]
Probar a poner la evolución en dos ejes:
* Horizontal para la fecha
* Vertical para el porcentaje de cumplimiento

**Comment by pr3ssh** [comment]
Se realiza una implementación funcional pero parcial para el lanzamiento de la v0.9. Se trabajará algo más tranquilo el tema para la v1.0.

**Comment by pr3ssh** [comment]
Dejamos en el eje XY los hitos ya pasados y con su grado de cumplimiento. Introducimos una nueva region en la que en una sola dimension mostremos los hitos a modo de hoja de ruta.
