### ISSUE TITLE
Definir sistema de roles

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#17]

**Comment by CIECODE** [comment]
Posibles roles:
- Super administrador
- Diferentes permisos (crear y/o actualizar causas de presión; dar de alta hitos)

**Comment by AnaMariaCM** [comment]
Según reunión Poletika AG 2/12/2016, todos de acuerdo con el articular diferentes roles y ser cuidadosos y responsables. Queda en manos de Ciecode, OI, PdI o NME proponer la estructura concreta de roles.

**Comment by pr3ssh** [comment]
Ok! Cualquier cosa que se necesite al respecto me la comentáis.

**Comment by AnaMariaCM** [comment]
He propuesto al compañero Felipe Giner que si él puede hacer el primer intento para definir el sistema de roles y me ha dicho que sí, que lo intenta una vez que vean cómo estamos planteando la web y el trabajo. Felipe es voluntario de Poletika y trabaja en Médicos del Mundo, ahora mismo preparando la nueva web. 
@pr3ssh , ¿puedes incluirle en este grupo de trabajo de Poletika? Su usuario github es @FelipeGiner, email giner.felipe@gmail.com. Mil gracias!

**Comment by pr3ssh** [comment]
@poletika/managers hecho!

**Comment by AnaMariaCM** [comment]
Gracias Pablo! Por favor, ¿puedes darle el mismo acceso que a mi o a Javi? así puede tener cierta visión general y ver todos los issues (me comenta que sólo puede acceder a su tarea, y yo creo que es importante que pueda unirse/ver todo, sí?) Mil gracias. Ahora que echamos de menos a Pablo2 y Julio, snif snif.

**Comment by pr3ssh** [comment]
@AnaMariaCM @FelipeGiner Ya está como *owner*, auque creo que antes también tenía acceso a todo ya que el proyecto está en abierto.

**Comment by FelipeGiner** [comment]
Lanzo una posible estructura base de roles. Seguro que hay matices y precisiones a incorporar.
1. **Superadministrador**. Acceso a gestión completa de la web, configuración, añadir/quitar widgets y plugins, gestión usuarios de cualquier rol (alta, baja y edición), acceso y gestión en hosting. Y además, lo comprendido en los roles siguientes.
2. **Webmaster o administrador**. 
- Alta/baja/edición de todas las causas de presión: subir imágenes, edición textos, creación de páginas
- Alta/baja/edición de todas las páginas estáticas
- Creación, edición y eliminación de contenido en blog
- Creación, modificación y eliminación de usuarios con rol de gestores de contenidos.

3. Gestor de contenidos. (este rol es el que se podría asignar a las organizaciones participantes de #poletika )
- Alta/baja/edición de causas de presión de su área de actuación (cooperación, sanidad, fiscalidad...)
- Alta/baja/edición de páginas estáticas creadas con ese usuario específico (no podrá modificar páginas creadas por otros usuarios)
- Creación, edición y eliminación de entradas en el blog creadas por ese mismo usuario.

**Comment by AnaMariaCM** [comment]
Muchísimas gracias @FelipeGiner. Desde la ignorancia, estoy de acuerdo en todo y me suena muy razonable. Apunto: 1) En el rol de 'gestor de contenidos', ¿se debería añadir el alta/baja/edición de la línea del tiempo o hitos que muestra la evolución de una causa de presión, o está incluido ya en la alta/baja/edición de causas de presión creadas por el usuario? Gracias por la aclaración (es decir, ¿el gestor de contenidos podrá editar todos los items/'contenidos' que haya dentro de su causa de presión, incluyendo la visualización de la evolución de esa causa? Gracias!). 
2) Roles - Entiendo que Oxfam Intermón asumiría el rol de super administrador. Entiendo que desde luego @pr3ssh estaríais ahí hasta que nos dejéis solitos 2 meses después del lanzamiento, ¿correcto? @CIECODE , ¿dónde os véis vosotros, Javi? 
3) Por mi ok a todo y a la espera de los comentarios de Javi, con más criterio. Por otro lado, creo que las organizaciones Poletika estarán muy de acuerdo con esto. Lo podemos presentar en enero.

**Comment by pr3ssh** [comment]
Gracias @FelipeGiner por la propuesta. Voy a recoger lo básico de la misma y lo voy a llevar a la tarea #18 para que luego se tenga claro qué es lo que hay que ejecutar. En tal caso para finales de enero los contenidos los cargaremos todos nosotros para que no haya problemas antes de haber dado la formación asi que para el segundo *milestone* se implementará este sistema de roles.
