### ISSUE TITLE
implementar sistema de roles

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#18]
**Administrador**
* Acceso a gestión completa de la web
* Configuración, añadir/quitar widgets y plugins
* Gestión usuarios de cualquier rol (alta, baja y edición)
* Lo comprendido en los roles siguientes.

**Manager**
* alta/baja/edición de todas las áreas temáticas (con sus acciones y pildoras)
* Alta/baja/edición de todas las causas de presión
* Creación/edición y borrado de hitos de una causa
* Creación/edición y borrado de pildoras de contenidos de una causa
* Creación/edición y borrado de acciones de una causa
*Alta/baja/edición de todas las páginas estáticas
* Creación, modificación y eliminación de usuarios con rol de gestores de contenidos.

**Gestor de contenidos**
*Este rol es el que se podría asignar a las organizaciones participantes de #poletika*

* Alta/baja/edición de causas de presión de su área de actuación (cooperación, sanidad, fiscalidad...)
* Creación/edición y borrado de hitos de una causa
* Creación/edición y borrado de pildoras de contenidos de una causa
* Creación/edición y borrado de acciones de una causa

------------------------

Nota: La gestión del hosting (servidor web) va por otro lado pero se compartirán las claves para que se pueda acceder.

**Comment by spolpen** [comment]
@AnaMariaCM Estamos valorando diversas soluciones de cara a la implementación del rol 'Gestor de contenidos' (según áreas temáticas) y se nos plantea una duda. ¿Habrá un único usuario compartido para administrar el contenido de cada área temática o múltiples usuarios lo administrarán?

**Comment by AnaMariaCM** [comment]
Hola @spolpen . Disculpad: ¿qué queréis decir exactamente con un único usuario compartido o múltiples usuarios? No conozco las diferencias (ventajas/desventajas) entre una opción y otra.  "Desde fuera", entiendo que si una temática es liderada por 2 organizaciones (ejemplo, fiscalidad, con InspirAction y OI), cada una debe tener un usuario para poder administrarla, ¿sí?

**Comment by spolpen** [comment]
@AnaMariaCM Me refiero a eso que indicas. Por ejemplo, para gestionar el área fiscalidad habría dos opciones:
- Un único usuario 'Fiscalidad' que podría administrar tanto InspirAction como OI
- Un usuario 'InspirAction' y otro usuario 'OI' que podrían administrarla

**Comment by AnaMariaCM** [comment]
Yo creo que un usuario único y que compartan como buenos hermanos. Si no tiene ninguna diferencia más... yo veo bien que sea un usuario único compartido @spolpen Gracias!
