### ISSUE TITLE
Generar páginas estáticas

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#22]
* Sobre el proyecto
* Contacto
* Poletika en el mundo
* ...

**Comment by pr3ssh** [comment]
Hay que definir qué páginas se necesirarán y los contenidos de las mismas.

**Comment by AnaMariaCM** [comment]
@CIECODE @pfariashuanqui Propuesta:  Entiendo que las páginas estáticas que queremos tener son un 'quiénes somos' y las FAQS. Propuesta de reparto de tareas: 
1) Pablo, ¿puedes revisar tú los textos actuales-FAQS de "quiénes somos", "qué pedimos", "qué temáticas vigilamos"? Habrá que actualizar algunas cosas, adaptar a la nueva fase de seguimiento de medidas legislativas y parlamentarias;
2) Javi, ¿podrías tú revisar y actualizar la parte de metodología, que está muy desfasada! -habría que explicar un poco al menos cómo hicimos el análisis del 26J, que comparamos con la XI Legislatura y con programas del 25D-, y la de "cómo puedo consultar los datos"? 
3) Yo me ocupo de adaptar el "a quién vigilamos y cómo", "qué puedes hacer tú", "cómo puedo ponerme en contacto con vosotros", -aunque esto dependerá de si la gente se puede suscribir? Y también me ocupo del "Poletika en el mundo". 

¿Alguna página estática más? ¿Alguna donde específicamente expliquemos las fases I y II y ahora el cambio hacia la III? Aunque esto puede estar incluido dentro de las FAQS... Un "Sobre el proyecto", como proponía Pablo-Enreda. También me puedo ocupar yo de hacer una propuesta para esto.

¿Cuándo podemos tener esto listo? Yo me puedo comprometer para el miércoles 14-Dic a las 13h. ¿Es muy tarde @pr3ssh ? ¿Qué os parece?

**Comment by pr3ssh** [comment]
@AnaMariaCM No nos harán falta en el corto plazo. Es para qe se vayan preparando los contenidos (textos, vídeos e imágenes) de cada una de ellas para que sobre el 10 de enero estuvieran.

**Comment by AnaMariaCM** [comment]
Y tan sólo 14 días tarde :-P, aquí va el texto de las páginas estáticas: Qué es Poletika, Qué hacemos en Poletika, Cómo ser Poletika y Por qué Poletika, además de las 2 'antiguas' Qué Dicen y Sus Programas. 
Esta no es una versión definitiva pero no creo que cambie mucho. Lara está revisando la sección 4. @CIECODE siéntete libre de revisar, tras Trump? @pr3ssh me dices si nos sirve o si hace falta algo más. Gracias.
[Páginas estáticas 24-1-2016 AC.docx](https://github.com/poletika/poletika.org/files/725836/Paginas.estaticas.24-1-2016.AC.docx)
En drive: https://docs.google.com/document/d/1RCiVj5ndzCUQcQ8Kr0F9Vt7V0mxkBNjiJURQ5udTFHo/edit?usp=sharing
