### ISSUE TITLE
Añadir Google Analytics al botón de descarga del informe d elos 100 días

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#26]

**Comment by AnaMariaCM** [comment]
Gracias por esto! Aprovecho. Debemos ser capaces de trackear:
- Las urls de las 5 causas de presión
- Nos interesa el nº de usuarios únicos, más que el nº de visitas
- Nos interesa el tiempo medio empleado por el usuario: cuánto está en la página
- Nos interesa cuál es la página de entrada, tránsito, salida, etc. 
Ya me callo. Gracias.

**Comment by pr3ssh** [comment]
@AnaMariaCM Esto realmente lo puse aquí para que no se me olvidara pero es una parte de lo que vamos a implementar en #15 
Cierro esta y me llevo tus comentarios a la otra.
