### ISSUE TITLE
Introducir etiquetas de SEO en la web

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#28]

**Comment by spolpen** [comment]
@AnaMariaCM Revisando las etiquetas SEO uno de los aspectos a mejorar es definir las keywords de la web. ¿Podríais  pasarnos un listado breve?

**Comment by AnaMariaCM** [comment]
@spolpen Estamos en ello. Lo tendremos la semana que viene. ¿Qué día lo necesitaríais? Gracias.

**Comment by AnaMariaCM** [comment]
Hola @spolpen Resulta que google analytics no nos da búsqueda de palabras clave, así que vamos a ciegas con este tema. Según dos compañeros, de momento podríamos avanzar con estas 3: son las que más búsquedas parecen suscitar de un listado inicial: buen gobierno, participación ciudadana y políticas públicas. ¿Es suficiente para avanzar algo?

**Comment by pr3ssh** [comment]
@spolpen Ponemos esas palabras clave (aunque sean pocas) y ya se irá optimizando.
