### ISSUE TITLE
Plantear solución para las imágenes en el sistema

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#32]
* Ver qué hacer en los widgets (cuando se pasa a pantalla media se queda un hueco). Habría que optar por una solución del tipo crop como teníamos antes pero mejor desarrollada.

* Ver cómo incluir una nota debajo de cada imagen con la autoría de la misma.

* Ver cómo dentrar las imágenes en el slider de la causa o en tal caso poner un lightbox para que al hacer click se abra como popup para que se pueda ver mejor.

**Comment by spolpen** [comment]
@AnaMariaCM ¿La nota con la autoría de la imagen iría en todas las imágenes, independientemente de si se encuentra como cabecera de un área, en una causa o en el slider?

**Comment by AnaMariaCM** [comment]
@spolpen Sí. Supongo que lo más discreto sería ponerlo en el extremo inferior derecho? Gracias

**Comment by spolpen** [comment]
@AnaMariaCM  Adjunto una propuesta, creo que lo mejor sería que apareciera cuando pasas el ratón por encima de la fotografía para no recargar p.ej. la página principal con el header, las causas y demás.
![autoria](https://cloud.githubusercontent.com/assets/9380577/22833896/c390228a-efb3-11e6-8fb1-77d273c22531.png)

**Comment by AnaMariaCM** [comment]
Perfecto. Muy buena idea. Interpreto q lo importante no es q se vea la autoría, sino q esté reconocida. Gracias.

**Comment by AnaMariaCM** [comment]
Hola @spolpen . Siento mucho esto. Parece no tener fin. Los compañerxs de educación me avisan que el cambio que se ha hecho en el carrusel es raro. Resulta que en lugar de subir la última foto que os pasé, y que adjunto aquí, la 11.26.49., se ha puesto 1 foto repetida 2 veces. Esta foto debe sustituir a 1 copia de las 2 repetidas. Por tanto, quedaría la foto que hay ahora de portada (fantástica), + 1 foto de 2 niños con un rotulador + 1 foto pizarra con una profesora 'velada-borrosa' + esta foto 11.26.49. 
Muchas gracias. Buen fin de semana.
![captura de pantalla 2017-01-23 a las 11 26 49](https://cloud.githubusercontent.com/assets/23697538/22839880/8b8328c0-efcb-11e6-92a8-c71736a02d56.png)

**Comment by pr3ssh** [comment]
@AnaMariaCM Es otra cosa diferente al motivo de este *issue*. En tal caso ya lo he corregido. Estaba a la espera de que el diseñador nos enviara la foto con la marca de autoría pero cuando nos la envíe cambio la actual y listo.

**Comment by AnaMariaCM** [comment]
Ah, ok, disculpad. Lo ligué con el tema de la autoría, sorry. Debe ser la frescura que llevamos encima... Gracias Pablo. Todo claro.

**Comment by pr3ssh** [comment]
Ya. Estamos como recién empezando... HAHAHA

Pablo Martín Muñoz
Hacker Cívico
