### ISSUE TITLE
Páginas temáticas 

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#36]
Recopilo en este issue 3 tareas principales respecto de las páginas temáticas, para no crear tantos issues como cuestiones concretas. Si preferís hacerlo de otro modo, me decís. Gracias:
1) Páginas temáticas sin causa de presión: acordamos buscar una solución 'gráfica' para las páginas temáticas que no tuvieran causa de presión activa. Dijimos que estas páginas no podían quedar 'vacías' en ese bloque, sino buscar una solución 'gráfica-visual', bien sea poner un vídeo, una imagen, un... ¿propuestas? 
(Páginas temáticas sin causas de presión: cambio climático, género, infancia, protección social, salarios y transparencia). 
2) En las páginas temáticas que tienen causa de presión: En el caso de que solamente exista una causa de presión en un área temática, y puede ser algo frecuente, esta se visualiza en  el margen izquierdo, existiendo demasiado aire en el resto de la página. Debería existir alguna solución para que en estos casos la imagen y texto cambiaran resize y ocuparan centro de la página. Hay 3 comentarios en el exce-drive-testeo en este sentido: están desalineados el título 'causa de presión' y la causa en sí, queda mucho 'espacio-aire' debajo al queda la causa alineada a la izquierda, etc. 
3) Repositorio en las páginas temáticas. Si recuerdo bien, hablamos de buscar una solución para que las páginas temáticas pudieran contener en un lugar concreto información o documentación básica referente a esa causa, fácilmente accesible para el usuario, sin necesidad de ir a las píldoras de contenidos, que además irán bajando/desapareciendo según pase el tiempo y se vayan añadiendo nuevas píldoras. Hemos de buscar la forma de ese repositorio (u otra solución que permita esto: acceder de forma fácil a información clave de esa temática).
Conectado con esto, recupero y añado un tema que ya salió en la 1ª entrega de la web, y es el lugar o la accesibilidad de las plantillas de indicadores y metas de cada temática en sus páginas temáticas. Las subimos como píldoras de contenidos como 'solución de emergencia', y fue genial. Ahora habría que buscar de qué manera visibilizarlas mejor y así dotar de mayor contenido a las páginas temáticas. Creo que si se crea el repositorio, ya tendríamos la solución a esto. 
Gracias.

**Comment by spolpen** [comment]
Cierro y divido en subtareas
