### ISSUE TITLE
Causas de presión: tuits predeterminados exceden caracteres

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#38]
Varios tuits predeterminados en las causas de presión exceden los 140 caracteres. Revisados ya todos los tuits de las causas de presión, estos serían los cambios a hacer: 
**1. Causa de presión de fiscalidad:** ahora mismo excede por 6 caracteres. Cambiar por: "@Haciendagob y C.Montoro, plantad cara a los paraísos fiscales. Plan de choque contra el fraude ya! #escaqueofiscal
poletika.org/node/91"
**2. Causa de cooperación 0,24%:** cambiar el actual por: .@GPSocialista @CiudadanosCs queréis el 0,4% en Cooperación n 2020: defended el 0,24$ AOD en 2017 #100DíasdeGobierno http://www.poletika.org/causa/aumento-presupuesto-cooperacion 
**3. Causa de educación**: _cambiar el primero por_: @educaciongob El Pacto Educativo debe contar con la participación d la comunidad educativa:#DiálogoPorLaEducación ya
poletika.org/causa/nueva-ley-educacion
_Cambiar el segundo twitter (el dirigido al PSOE) por_:   @gpscongreso deroga la LOMCE como prometiste e impulsa #DialogoPorLaEducación según programa PSOE #100DíasdeGobierno http://www.poletika.org/causa/nueva-ley-educacion 
**4. Causa de refugiados**: c_ambiar el primero actual ('pide a Rajoy...') por:_ ¿Te escandaliza Trump? Pide a @marianorajoy que los refugiados comprometidos vengan a España ya #derechoarefugio
poletika.org/causa/compromiso-acogida-refugiados 
_Cambiar el segundo_ ('trae a los refugiados con quien te has comprometido') por: @Rajoy @gpscongreso @CsCongreso @PodemosCongreso trae a ls refugiadxs con quienes te comprometiste!#derechoarefugio poletika.org/causa/compromiso-acogida-refugiados

**Comment by spolpen** [comment]
@AnaMariaCM Actualizado el primer tweet. 
El motivo por el que han excedido los caracteres es que, independientemente del tamaño de la URL que se enlace (ya sea externa o a alguna sección de Poletika), Twitter utiliza 23 caracteres para ello, por lo que el tamaño útil para la información y el hashtag es realmente de 117 caracteres.

**Comment by AnaMariaCM** [comment]
@spolpen Muy bien. Recién revisé y actualicé todos los acciona-tuit de las causas de presión. Actualicé el comentario de arriba con los cambios a hacer. Gracias.
