### ISSUE TITLE
Causa de presión de fiscalidad - cambiar texto de párrafo descriptivo

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#39]
El párrafo descriptivo de esta causa de presión (entre el bloque de acciones y el carrusel de imágenes), debe ser: 
"El sistema tributario español pierde cantidades ingentes de recursos por las prácticas de evasión y elusión fiscal. El Gobierno ha de impulsar con carácter urgente una ambiciosa batería de medidas para reducir significativamente los niveles de fraude fiscal. Entre ellas deberían estar:
- Revisar la definición de paraísos fiscales. 
- Zonas libres de paraísos fiscales: contratacion pública que priorice a empresas sin vínculos con paraísos fiscales.
- Transparencia y rendición de cuentas: Hacer obligatorio para todas las grandes empresas y con carácter público el reporte financiero país por país, implantar un registro público obligatorio de titulares reales y
últimos de las empresas.
- Asegurar una dotación extraordinaria en recursos económicos y humanos para la agencia tributaria.
- Revisión exhaustiva y rigurosa de todos los incentivos, deducciones y exenciones fiscales."

**Comment by spolpen** [comment]
Actualizado
