### ISSUE TITLE
Sistema de áreas temáticas

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#4]
El sistema debe permitir por cada área:
* Nombre
* Explicación de la temática
* Una serie de causas de presión
* Una serie de píldoras de contenidos
* Una serie de acciones

Y luego que cada área temática pueda marcarse como prioritaria o no y que eso tenga un impacto en cómo se muestre la info en la web.

**Comment by pr3ssh** [comment]
Notas de maquetación y diseño:

* Tenemos que mostrar las causas de presión activas y archivadas en la vista de una temática.
* Las causas de presión se deberían de ajustar al ancho de la página según número de ellas (1 a pantalla completa, 2 a 50% cada una, etc).

/cc @spolpen @pablovg2

**Comment by AnaMariaCM** [comment]
@pr3ssh Aloha! Aquí adjunto como modelos: 1) fichas temáticas de salarios, protección social y conflictos internacionales para modelo-ejemplo de páginas-temáticas. 2) ficha de conflictos internacionales para modelo de causa de presión (es el mismo doc de conflictos internacionales). Pablo, verás que estas fichas-plantillas tienen comentarios/modficiaciones con control de cambios. No hagas caso/acéptalos todos. Son comentarios míos que deben ser acordados con las personas líderxs de estas plantillas, pero como nos urge la cosa y no son cambios sustanciales, creí que era mejor pasártelos ya como modelo-ejemplo, por si se puede empezar a montar algo. Gracias! Abrazo.
[Conflictointernacional PS19-1-2017 + AC.docx.docx](https://github.com/poletika/poletika.org/files/726297/Conflictointernacional.PS19-1-2017.AC.docx.docx)
[Plantilla Web Poletika Protección Social +AC.docx](https://github.com/poletika/poletika.org/files/726298/Plantilla.Web.Poletika.Proteccion.Social.AC.docx)
[PlantillaWebPoletikaSalarios +AC.docx](https://github.com/poletika/poletika.org/files/726299/PlantillaWebPoletikaSalarios.AC.docx)

**Comment by AnaMariaCM** [comment]
Uy, Github dice que he cerrado y he reabierto este issue ahora mismo, todo en uno. Lo siento: ha sido sin querer... Aquí adjunto la foto/imagen que iría con la causa de presión de refugiados. Esta va en baja resolución. La tenemos en güena-güena. Autoría: Pablo Tosco, Oxfam Intermón.
![foto causa refugiados oes](https://cloud.githubusercontent.com/assets/23697538/22243148/61084aec-e226-11e6-9552-017c1a98167e.jpg)

**Comment by pr3ssh** [comment]
@AnaMariaCM Gracias! Los vamos revisando y en tal caso integrando para ver cómo va quedando.
