### ISSUE TITLE
Cuestiones generales causas de presión

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#40]
Para no abrir tantos issues sobre cuestiones menores, abro 1 issue que aglutine varias cuestiones generales, en este caso, relativas a las causas de presión. Durante el miércoles 22 iré completando-anotando las cuestiones que vaya recuperando del excel o que se hayan visto antes y estén pendientes. 
Si preferís trabajarlo de otra forma, me decís. Gracias:
**1. Logos:** En las causas de presión vigiladas por Oxfam Intermón y otra organización (fiscalidad, cooperación), los logos quedan extraños: ¿se pueden cuadrar mejor, hacer más iguales de tamaño y encuadre? Ejemplo: tal y como se ven en la causa de presión de salud sería perfecto;
**2. La letra del párrafo descriptivo** que está entre el bloque de acciones y el carrusel de imágenes es muy pequeña. Apenas se puede leer y contrasta con el resto de la página. ¿Se puede ampliar? 
**3. Gráficamente,** se ve extraño el encabezamiento de las causas: el título a la temática asociada está justificado, la imagen centrada, luego los logos y el % de logro, y de repente el título de la causa alineado a la izquierda. ¿Se puede probar otra solución gráfica, todo justificado o todo alineado? 
**4. Títulos auto-explicativos:** hay diversos comentarios apuntando la necesidad de clarificar las diferentes secciones que hay en las causas de presión. Poner títulos que clarifiquen las diferentes secciones: 
     A. "Presiona", para el bloque rojo de acciones en facebook y Twitter, y que podrá incluir también acciones en Change u otras, si alguna causa las incluye en el futuro, ¿correcto? 
     B. "Momentos clave" o algo así para la línea del tiempo-hoja de ruta...?
     C. "Esta causa, ¿avanza?", para la gráfica de evolución/porcentaje de la causa;
     D. "¿Qué está pasando?" para las píldoras de contenidos (o un "Noticias" o un "Actualidad").
**5. El bloque rojo con las acciones queda demasiado grueso** cuando hay más de 3 acciones: se podría hacer más fino este bloque, y las diferentes secciones, para que quede todo más 'encuadrado' y no tener que hacer tanto scroll? Cuesta mucho tener una 'visión rápida' de la causa porque obliga a bajar demasiado. Si además vamos a incluir otro bloque más con la gráfica de medición-evolución, creo que tendríamos que encontrar una solución donde todo encaje mejor. Que se puedan ver más cosas de 'un vistazo'. Gracias.
**6. Copyright de las fotografías:** hay que añadir el copyright de las fotografías a las causas de presión de refugiados, fiscalidad, cooperación y sanidad. Sí está en educación: se ve en la foto grande de la causa, pero no en las pequeñas del carrusel (está tan pequeño que es imposible leerlo). Enreda hizo una propuesta de que el copyright apareciera en una especie de banda/línea que solo apareciera cuando el usuario pasa por encima: ¿sigue en pie, podemos verlo? Si no, creo que una solución para el copyright de las fotos que van en el carrusel sería, no ponerlo dentro de cada foto, sino poner una especie de 'pie de foto' general para todo el carrusel explicitando el copyright, dado que es el mismo para las 3 fotos del carrusel (al menos en los casos de educación, refugiados, cooperación y fiscalidad; Ana Claver comprobará sanidad, pero creo que también será el mismo). Gracias.

**Comment by spolpen** [comment]
Cierro y divido en subtareas
