### ISSUE TITLE
Páginas estáticas Home-Footer

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#41]
Hola. Agrupo aquí varias cuestiones relativas a las páginas estáticas "quién es Polétika, qué hacemos en Polétika, etc", que van en el footer de la home. Gracias:

1) En el footer aparecen 4 páginas estáticas: quién es Polétika, qué hacemos en Polétika, cómo ser Polétika, por qué existe Polétika. Sin embargo, cuando una pincha y va a las páginas, el nº de secciones-apartados es distinto (hay 7, no 4) y los títulos de las secciones son diferentes: en algunos casos, se mantienen los títulos antiguos, no los nuevos. Ejemplo: dice "quiénes somos", no "quién es Polétika"; dice "Qué hacemos", no "Qué hacemos en Polétika". Y mantiene diferenciadas las secciones "Qué Vigilamos, A quién Vigilamos, Metodología", cuando en la propuesta de texto la intención era subsumir estas secciones en el "Qué hacemos en Polétika". Viéndolo ahora, entiendo que 1 sola sección "Qué hacemos en Polétika" que incluya las otras 3 secciones, quedaría enorme. Propongo:
**2) Mantener las 7 secciones actuales**, pero ajustar el nº de secciones y los títulos en el footer y en las páginas estáticas una vez que pinchas y te llevan allí. Ejemplo: si decimos en el footer Qué es Polétika, la página estática se debe titular Qué es Polétika. No estoy segura sobre el nº de secciones: entiendo que meter los 7 títulos en el footer puede ser demasiado para el footer. ¿Qué pensáis vosotros? Gracias.
**3) Cambiar el texto actual** de algunas de 2 de las páginas estáticas por el adjunto debajo (drive). Visto como queda una vez publicado, había que mejorar y acortar el texto de algunas secciones. 
**4) Páginas estáticas y menú hamburguesa:** varios comentarios apuntaban que el menú-hamburguesa solo con las temáticas no era muy intuitivo y podía mejorar en claridad (o que era difícil entender qué es Polétika si entras por primera vez a la home), añadiendo alguna de estas secciones estáticas. Propongo añadir al menú-hamburguesa "Qué es Polétika" y "Cómo ser Polétika", ¿os parece? Por priorizar y no meter todo. Y que en el footer sí aparezcan todas las páginas estáticas.
**5) Sección Qué Vigilamos:** en la web antigua, cada una de estas temáticas llevaba un pdf-posicionamiento vinculado con más información sobre esa temática. No todas las temáticas tenían este pdf-posicionamiento, pero la mayoría. Es importante recuperarlos de la web antiguo y volver a enlazarlos aquí. @pr3ssh proponía ponerlos en la página de la temática en cuestión. Yo creo que es bueno ponerlo en los 2 lados: aquí, en la sección estática de Qué Vigilamos, y en las páginas temáticas que correspondan, cuando tengamos resuelto el repositorio. 
Además, Ciecode proponía que aquí, si pinchas el nombre de la temática, te lleve a la página-estática de esa temática. Gracias.
**6) Sección Metodología:** el documento-pdf adjunto se ha de actualizar. @CIECODE y Ana Claver se coordinan para hacerlo y lo envían a Enreda. 
**7) Sección "Cómo ser Polétika":** de algún modo diferenciar mejor gráficamente las diferentes opciones de colaboración que se dan al usuario: bien con bullet points, o de alguna forma numerada o algo 'atractivo'. Tal y como está ahora creo que se ve mucho texto y podríamos hacerlo un pelín más atractivo. Gracias.

**Texto final de las secciones Cómo ser Polétika y Por qué existe Polétika.** El texto final de estas 2 secciones es el primer texto que aparece nada más comenzar el documento. Cualquier duda, me decís. Gracias:
https://docs.google.com/document/d/1RCiVj5ndzCUQcQ8Kr0F9Vt7V0mxkBNjiJURQ5udTFHo/edit?usp=sharing

**Comment by spolpen** [comment]
Buenas @AnaMariaCM, adjunto tres propuestas respecto al menú tal y como indicas en el punto 4.
![menu1](https://cloud.githubusercontent.com/assets/9380577/23459283/fc350288-fe7f-11e6-9962-92e6fec8e64f.png)
![menu3](https://cloud.githubusercontent.com/assets/9380577/23459284/fc376456-fe7f-11e6-8f08-27ec8a08c936.png)
![menu2](https://cloud.githubusercontent.com/assets/9380577/23459285/fc42d976-fe7f-11e6-938a-1892da266e2a.png)

**Comment by pr3ssh** [comment]
IMHO dejaría el menú hamburguesa como acceso rápido a las temáticas y el resto de cosas las dejaría en el footer como hasta ahora. Es una cuestión de priorizar info pero vosotras mandáis.

**Comment by spolpen** [comment]
Cierro y divido en subtareas
