### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#42]
Hola. Agrupo algunas cuestiones-tareas relativas a la home. Se incluyen las identificadas en el excel-drive de testeo:
**1. Título de Polétika, Vigilancia y presión ciudadana para el cambio político**: sigue siendo muy pequeño. ¿Hay opción a ponerlo un poco más grande?
**2. Menú-hamburguesa:** lo ya apuntado en el issue sobre páginas estáticas: incorporar al menos el Quién es Polétika y el Cómo ser Polétika. 
**3. Menú-hamburguesa:** todas las temáticas aparecen en orden alfabético menos conflictos internacionales. 
**4.  Línea divisoria o título explicativo para las causas de presión:** Debajo del faldón del Congreso, del bloque que ahora tiene la foto del léon y el análisis de los 100 días, y que luego será el carrusel de causas de presión, añadiríamos un texto tipo: "Causas de presión" o "Presiona para que se cumplan" y debajo las 5 acciones para ganar claridad. 
**5. Marcador de cumplimiento de las causas en la home**: Creemos que el marcador de cumplimiento debajo de la foto de la causa es tan sutil que es casi imposible que la gente entienda lo que significa. Sabemos que es una solución temporal pero, ¿sería posible poner un 0 y un 100% a cada lado o poner el % que corresponda al lado de la barra coloreada? Para el 10 de marzo: ¿podemos tener la propuesta definitiva para esta barra de progreso? Habíamos propuesto algo tipo "batería de móvil cargándose", y que fuera apareciendo tramos de cumplimiento: 25%, 50%, etc. ¿Cuál es la solución definitiva? ¿Podemos verla? Gracias.

**Comment by spolpen** [comment]
Cierro la tarea para dividirla en subtareas
