### ISSUE TITLE
[Front] Menú-hamburguesa

### ISSUE THREAD

**Issue by spolpen** [poletika/poletika.org#44]
- Incorporar al menos el Quién es Polétika y el Cómo ser Polétika.
- Todas las temáticas aparecen en orden alfabético menos conflictos internacionales

**Comment by spolpen** [comment]
@AnaMariaCM Dejo aquí las propuestas del menú.
![menu1](https://cloud.githubusercontent.com/assets/9380577/23475416/d6da0e4c-feb7-11e6-97ea-8b92fc468aca.png)
![menu3](https://cloud.githubusercontent.com/assets/9380577/23475417/d7026cd4-feb7-11e6-9ad3-d1be3251e89d.png)
![menu2](https://cloud.githubusercontent.com/assets/9380577/23475418/d70d1166-feb7-11e6-8dfb-e305fb0917b7.png)

Comentario de @pr3ssh en la tarea anterior: 

> IMHO dejaría el menú hamburguesa como acceso rápido a las temáticas y el resto de cosas las dejaría en el footer como hasta ahora. Es una cuestión de priorizar info pero vosotras mandáis.

**Comment by AnaMariaCM** [comment]
@spolpen @pr3ssh Muchas gracias. Adelante con la 1ª. Es estupenda. Solo 1 corrección: lo que queremos poner en el menú es Qué es Polétika (como Qué Hacemos) y Cómo ser Polétika. Gracias!
