### ISSUE TITLE
[Estática] Sección Qué Vigilamos

### ISSUE THREAD

**Issue by spolpen** [poletika/poletika.org#49]
En la web antigua, cada una de estas temáticas llevaba un pdf-posicionamiento vinculado con más información sobre esa temática. No todas las temáticas tenían este pdf-posicionamiento, pero la mayoría. Es importante recuperarlos de la web antiguo y volver a enlazarlos aquí. @pr3ssh proponía ponerlos en la página de la temática en cuestión. Yo creo que es bueno ponerlo en los 2 lados: aquí, en la sección estática de Qué Vigilamos, y en las páginas temáticas que correspondan, cuando tengamos resuelto el repositorio.
Además, Ciecode proponía que aquí, si pinchas el nombre de la temática, te lleve a la página-estática de esa temática. Gracias.

**Comment by spolpen** [comment]
@AnaMariaCM Hemos recuperado de la web antigua 10 PDFs correspondientes a cada temática (todas menos género) denominados matriz_TEMA.pdf. Son los PDFs que deben ir aquí, ¿cierto?
Los adjunto por si es necesario revisarlos.
[matriz_sanidad.pdf](https://github.com/poletika/poletika.org/files/857652/matriz_sanidad.pdf)
[matriz_infancia.pdf](https://github.com/poletika/poletika.org/files/857653/matriz_infancia.pdf)
[matriz_participacion.pdf](https://github.com/poletika/poletika.org/files/857654/matriz_participacion.pdf)
[matriz_proteccion_social.pdf](https://github.com/poletika/poletika.org/files/857655/matriz_proteccion_social.pdf)
[matriz_salarios.pdf](https://github.com/poletika/poletika.org/files/857656/matriz_salarios.pdf)
[matriz_cambio_climatico.pdf](https://github.com/poletika/poletika.org/files/857657/matriz_cambio_climatico.pdf)
[matriz_conflictos_internacionales.pdf](https://github.com/poletika/poletika.org/files/857658/matriz_conflictos_internacionales.pdf)
[matriz_desarrollo.pdf](https://github.com/poletika/poletika.org/files/857659/matriz_desarrollo.pdf)
[matriz_educacion.pdf](https://github.com/poletika/poletika.org/files/857660/matriz_educacion.pdf)
[matriz_fiscalidad.pdf](https://github.com/poletika/poletika.org/files/857661/matriz_fiscalidad.pdf)

**Comment by spolpen** [comment]
@AnaMariaCM Hemos recuperado de la web antigua 9 PDFs de la sección "Qué temáticas vigilamos". Están todas las áreas menos "Género" que no aparece y "Cambio Climático" que no enlaza a ningún PDF.
Los adjunto por si es necesario revisarlos.
[infancia.pdf](https://github.com/poletika/poletika.org/files/857688/infancia.pdf)
[conflictos_internacionales.pdf](https://github.com/poletika/poletika.org/files/857690/conflictos_internacionales.pdf)
[participacion.pdf](https://github.com/poletika/poletika.org/files/857689/participacion.pdf)
[salarios.pdf](https://github.com/poletika/poletika.org/files/857693/salarios.pdf)
[proteccion_social.pdf](https://github.com/poletika/poletika.org/files/857686/proteccion_social.pdf)
[educacion.pdf](https://github.com/poletika/poletika.org/files/857687/educacion.pdf)
[fiscalidad.pdf](https://github.com/poletika/poletika.org/files/857692/fiscalidad.pdf)
[desarrollo.pdf](https://github.com/poletika/poletika.org/files/857691/desarrollo.pdf)

**Comment by AnaMariaCM** [comment]
Hola @spolpen . No, no son estas. Estas son las so-called 'plantillas' de Polétika, que contienen las peticiones, indicadores y metas de cada temática. 
Los documentos-pdfs a los que me refería son documentos de posicionamiento. Es una pena porque son justo los documentos que no logro encontrar en las carpetas de Polétika. Adjunto el ejemplo del documento de infancia. Pues de este tipo (un documento más narrativo), había en casi todas las temáticas, excepto género y cambio climático, quiero recordar. **Localización**: pues en las FAQS, o en el Qué Pedimos, o yo quiero recordar que estaban vinculados-descargables desde el Qué Vigilamos, cuando enunciaba cada temática.
Si nos dais con ellos, los puedo pedir a cada organización y que me los envíen. Pero, conociéndonos a Polétika, creo que lo ideal sería recuperarlos de la web antigua.
Ya me decís. Gracias.

**Comment by AnaMariaCM** [comment]
[plataforma_infancia_politicas.pdf](https://github.com/poletika/poletika.org/files/857796/plataforma_infancia_politicas.pdf)

**Comment by spolpen** [comment]
@AnaMariaCM Revisa mi último comentario (puse un comentario con las plantillas que indicas pero fue error mío y lo actualicé precisamente con documentos de ese tipo, aunque no todos siguen el mismo formato por lo que no sé si serán definitivos). 
Perdona, aunque lo borrara te habrá llegado al correo, pero están actualizados en el comentario anterior.

**Comment by AnaMariaCM** [comment]
Cierto @spolpen , sorry. Adelante con estos últimos pdfs. Dejar fuera el de educación, sí? El resto, todos dentro.
Gracias.
