### ISSUE TITLE
[Estática] Sección Metodología

### ISSUE THREAD

**Issue by spolpen** [poletika/poletika.org#50]
El documento-pdf adjunto se ha de actualizar. @CIECODE y @AnaMariaCM se coordinan para hacerlo y lo envían a Enreda

**Comment by AnaMariaCM** [comment]
@spolpen Sergio, estamos en ello. Este documento-pdf va a ser de lo ultimito en llegar. Igual lo tenemos el jueves 9 de marzo o viernes 10 de marzo, ¿de acuerdo? Gracias.

**Comment by AnaMariaCM** [comment]
Hola @spolpen! Ya lo tenemos. Aquí adjunto el pdf actualizado de metodología por cortesía de @CIECODE . Gracias! 
[Metodología Polétika_Fases 1-2-3 VF.pdf](https://github.com/poletika/poletika.org/files/833695/Metodologia.Poletika_Fases.1-2-3.VF.pdf)
