### ISSUE TITLE
[Causas de presión] Logos

### ISSUE THREAD

**Issue by spolpen** [poletika/poletika.org#52]
En las causas de presión vigiladas por Oxfam Intermón y otra organización (fiscalidad, cooperación), los logos quedan extraños: ¿se pueden cuadrar mejor, hacer más iguales de tamaño y encuadre? Ejemplo: tal y como se ven en la causa de presión de salud sería perfecto;

**Comment by spolpen** [comment]
@AnaMariaCM Esto ocurre porque el logo de Oxfam es proporcionalmente más alto que ancho y los dos logos de las causas que comparte Oxfam son al contrario, en cambio en Salud p.ej. tienen la misma proporción.
¿Tenéis el logo de Oxfam con otras proporciones?

**Comment by AnaMariaCM** [comment]
@spolpen Aquí está el link a la política visual de Oxfam: espero que haya alguna forma de hacerlo más chico... http://www.oxfamintermon.org/minisites/identidadvisual/general.htm Gracias
