### ISSUE TITLE
[Temáticas] Repositorio en las páginas temáticas

### ISSUE THREAD

**Issue by spolpen** [poletika/poletika.org#59]
Si recuerdo bien, hablamos de buscar una solución para que las páginas temáticas pudieran contener en un lugar concreto información o documentación básica referente a esa causa, fácilmente accesible para el usuario, sin necesidad de ir a las píldoras de contenidos, que además irán bajando/desapareciendo según pase el tiempo y se vayan añadiendo nuevas píldoras. Hemos de buscar la forma de ese repositorio (u otra solución que permita esto: acceder de forma fácil a información clave de esa temática).
Conectado con esto, recupero y añado un tema que ya salió en la 1ª entrega de la web, y es el lugar o la accesibilidad de las plantillas de indicadores y metas de cada temática en sus páginas temáticas. Las subimos como píldoras de contenidos como 'solución de emergencia', y fue genial. Ahora habría que buscar de qué manera visibilizarlas mejor y así dotar de mayor contenido a las páginas temáticas. Creo que si se crea el repositorio, ya tendríamos la solución a esto.

**Comment by spolpen** [comment]
@AnaMariaCM ¿Los PDFs que se indican son los mismos que los de la tarea #49? 
De no ser así, ¿podrías aclararnos cuál es cada uno respectivamente?

**Comment by AnaMariaCM** [comment]
Hola @spolpen. Disculpa la tardanza en contestar: no me funcionaba el aviso automático de los emails :-/. Respuesta: son otros diferentes. Los de la tarea #49 era un documento de posicionamiento de las entidades que lideran esa temática. Debería haber 11, pero no se llegaron a elaborar todos. Estos documentos deberían recuperarse de la antigua web: sección Qué Vigilamos de la antigua web. 
A los que me refiero aquí, que deben ir vinculados a la página temática y como documento base del repositorio, es a estos: http://www.poletika.org/sites/default/files/2017-02/Plantilla_CambioClimatico.pdf
Para el 9 de febrero los pusimos como píldoras de contenidos, pero en realidad deberían estar bien visibles y accesibles en ese repositorio que creemos en cada home-temática, pues es el corazón de Polétika. Tenéis todos los pdfs ya subidos como píldoras de contenidos. Gracias. 
Si hay alguna duda, me decís.

**Comment by spolpen** [comment]
@AnaMariaCM Adjunto una propuesta para el repositorio de las páginas temáticas. El texto que aparece es un texto genérico a todas las causas, en el que se informe de que es un espacio que recopila la información de esa temática y lo que creáis conveniente.
Si os parece bien, quedo a la espera del texto para cerrarlo.
![repositorio](https://cloud.githubusercontent.com/assets/9380577/24147027/a9743f00-0e38-11e7-9031-f4473015e6a0.png)

**Comment by AnaMariaCM** [comment]
Hola @spolpen @pr3ssh . Propongo como texto "Accede a los documentos de análisis más importantes en materia de infancia". Y que cambie el nombre de la temática conforme a cada temática (valga la redundancia): es decir, "... en materia de desarrollo", "... en materia de género", "... en materia de salarios dignos", etc.
