### ISSUE TITLE
Autoría fotografías Cooperación al Desarrollo y Fiscalidad

### ISSUE THREAD

**Issue by spolpen** [poletika/poletika.org#61]
@AnaMariaCM ¿Podrías indicarnos la autoría de las fotografías de ambas causas de presión?

**Comment by AnaMariaCM** [comment]
Hola @spolpen . Aquí van:
**Para Cooperación son:** 
- Copyright foto principal: Oxfam Intermón
- Copyright fotos carrusel:
    - Foto manifestación Polochic (la que se ve un trozo de pancarta negra que pone 769 en naranja): Oxfam
    - Foto manifestación Comercio con Justicia: Pablo Tosco/Oxfam Intermón
    - Foto Pobreza Cero: Oxfam Intermón 

**Para Fiscalidad,** todas las fotos, principal y las 3 del carrusel, son de copyright Oxfam Intermón. 
**Para Refugiados,** todas las fotos (principal y las 3 del carrusel), son copyright Pablo Tosco/Oxfam Intermón.
