### ISSUE TITLE
Correcciones causa de presión Sanidad 

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#62]
Médicos del Mundo dice: En la línea temporal de hitos hay dos “problemas”:
o	Se hace mención a la sesión monográfica en la Cumbre Social, poniendo además como fecha el 17 de abril. Aunque las conversaciones para realizar dicho monográfico marchan bien, ni está aún 100% confirmada y menos con fecha concreta, con lo cual creo que es mejor que de momento no aparezca y ya lo añadiremos como hito cuando hayamos cerrado la organización, ya que de otro modo pueden molestarse algunxs de nuestrxs compas en la Cumbre. 
o	Marca como presentación del nuevo informe de REDER el 21 de abril. La presentación será el mismo 20 abril, aprovechando el aniversario. **Ana Claver (AC): ¿intuyo que esto igual es porque no se pueden poner 2 hitos, uno interno y otro externo, con la misma fecha? Gracias**.

**Comment by spolpen** [comment]
@AnaMariaCM Cierro esta tarea, con el nuevo formato de hitos no debería haber problemas por tener hitos con la misma fecha. 
Igualmente, cualquier tema lo hablamos en #72
