### ISSUE TITLE
Favor: Subir hoy píldora de contenido a home-temática Género 8 de marzo. 

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#63]
Buenos días @pr3ssh @spolpen Os pedimos un favor: dado que hoy es el día internacional de la mujer, ¿podríamos subir el contenido adjunto como píldora de contenido a la home-temática de género? Sería subir esta imagen adjunta, con este link a esta noticia https://pobrezacero.wordpress.com/2017/03/07/nosotras-mujeres-del-mundoparamos/ , y esta frase. "El 8 de marzo se celebra el Día Internacional de la Mujer. En 2017, colectivos, instituciones y movimientos feministas convocan marchas y paros internacionales en 46 países para reclamar igualdades reales de género. También en España."
Mil gracias!! 
![paramujeres-300x250](https://cloud.githubusercontent.com/assets/23697538/23698524/31b2cfe6-03ec-11e7-8231-85e5b79278f8.png)

**Comment by spolpen** [comment]
@AnaMariaCM Subida, ya podéis verla en http://poletika.org/tematica/genero

**Comment by AnaMariaCM** [comment]
Muchas gracias @spolpen . Puede ser que falte el link a este post? Es lo que dota de contenido a la píldora. Gracias! https://pobrezacero.wordpress.com/2017/03/07/nosotras-mujeres-del-mundoparamos/

**Comment by spolpen** [comment]
@AnaMariaCM Cierto, fallo mío perdona, ya lo actualicé.
