### ISSUE TITLE
Revisión de la hoja de ruta (hitos)

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#66]
Se añaden en los sucesivos comentarios las diferentes aportaciones.

**Comment by CIECODE** [comment]
Hola, 
Ahí van dos comentarios a la 'Hoja de Ruta' de la web de Polétika:
- Los nombres de los meses aparecen en inglés. Supongo que es fácil cambiarlo a español o ponerlo en el formato de fecha que estamos usando para las píldoras de contenido.
- Creo que sería útil el que se viera de forma intuitiva cuál es la 'dirección temporal' de los hitos. Básicamente, me refiero a que en el extremo inferior de la línea negra lateral hubiera una flecha apuntando hacia abajo.
- Me gusta la estética de los hitos (sencilla, clara y limpia) aunque me pregunto si en alguna ocasión vamos a necesitar meter algún subtítulo o pequeño texto de explicación y si eso está previsto.

**Comment by AnaMariaCM** [comment]
Hola. Aquí van mis comentarios:
1- Apoyo especialmente el comentario 2 de Ciecode. Es más, me pregunto: asumo que si hemos puesto los hitos en vertical es porque no se pueden poner en horizontal, ¿correcto? Porque me es más fácil entender la hoja de ruta temporal (línea del tiempo) en horizontal que en vertical. 
2- Sobre el comentario 3 de Ciecode: ¿qué posibilidades de 'contenidos extra' nos permite esta hoja de ruta? Además de esa 'frase extra' que dice Javi, ¿podemos meter un link, o que el título vaya linkado a algún sitio-información adicional sobre ese hito una vez que haya pasado? ¿o que al pinchar en el hito, nos lleve a la gráfica de valoración/progresión del hito? ... (ups).
3- Igual no procede en este hilo-issue, pero sugiero cambiar el título "píldoras de contenido" por el de 'Últimas noticias' o 'Noticias de Actualidad' o algo así.
Gracias.
