### ISSUE TITLE
Integración con TipiCiudadano.es

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#7]

**Comment by pr3ssh** [comment]
@CIECODE Para la inegración me surgen ciertas preguntas:

* Una causa puede estar relacionada con un solo tipi con con más de uno?
* Qué información del tipo nos debemos de traer para mostrarla en Poletika?

**Comment by CIECODE** [comment]
Hola @pr3ssh y @aleixx. 
- Creo que en la mayoría de los casos, una causa pertenecerá a un unico tema Tipi. No se me ocurre un caso en el que no vaya a ser así.
- Como yo lo había imaginado es: para cada causa de presión realizar una selección de los términos de UN ÚNICO diccionario que estén relacionados con esa causa y que sean los resultados de esa búsqueda lo que mostremos en Polétika. 
- Respecto a qué info mostrar: yo creo que todas las coordenadas obvias (autor, grupo, lugar, tipo de acto, fecha, estado de tramitación...). Respecto a los términos detectados, seguro mostraría los del diccionario en cuestión y dudo si también los términos que hayan saltado de otros diccionarios. 
- Creo que algo interesante es realimentarnos mutuamente: Tipi destacando (en redes sociales principalemente) los actos parlamentarios que Polétika considere clave (ya lo estamos haciendo) y Polétika atrayendo visitas desde su web a Tipi. Por eso yo de inicio pensaba que la conexión con Tipi se hiciera mostrando directamente 'resultados Tipi', pero quizá vosotros teníais pensado Más bien usar la materia prima de Tipi pero maquetarla y mostrarla de forma diferente...
Espero haber respondido más que liado. 
Abrazos. 
Javi

**Comment by pr3ssh** [comment]
Definitivo: Mostrar los 5 últimos actos de una búsqueda predeterminada (vía API) de un diccionario y términos. Se mostraría un esbozo para luego poder ampliarlo saltando a Tipi.

**Comment by CIECODE** [comment]
Hola @pr3ssh,

Genial, me pongo a elaborar el listado de términos en base al cual se realizará dicha búsqueda.

Ya tengo el de Educación, por si queréis ir haciendo pruebas: http://tipiciudadano.es/escaner?dicts=educaci%C3%B3n&terms%5B%5D=Derogaci%C3%B3n+LOMCE&terms%5B%5D=Ley+8%2F2013+para+la+mejora+de+la+calidad+educativa&terms%5B%5D=Ley+Wert&terms%5B%5D=LOMCE&terms%5B%5D=Pacto+por+la+Educaci%C3%B3n&terms%5B%5D=Pacto+de+Estado+Social+y+Pol%C3%ADtico+por+la+Educaci%C3%B3n&grupootro=&autor=&fechadesde=&fechahasta=&lugar=&ref=&vtipo=&tramitacion=&titulo=

Javi

**Comment by pr3ssh** [comment]
@aleixx Se ha cambiado el formato en el que se guardará la información de Tipi en una causa temática. ahora lo que se guardará es un *chorizo* tal que así

`http://tipiciudadano.es/api/v1/tipis?limit=5&dict=dependencia&terms=Asistencia+personal&terms=Anciano`

que es el que nos servirá directamente para hacer la petición a la API (o si no giardarlo sin el host).
Por ello hay que modificar el módulo para que trabaje con este tipo de valores.

**Comment by pr3ssh** [comment]
@aleixx Además habría que preparar para este issue y para el de #6 un *render_field* o algo similar en Drupal8 para que cuando se pinte el campo en cuestión en la ficha de la Causa se renderice el valor procesado y no el almacenado.

**Comment by pr3ssh** [comment]
@aleixx Otra opción es usar **Twig Helpers**. En [esta página](http://www.xenomedia.com/blog/top-thirteen-drupal-twig-helper-modules) tienes algunos ejemplos de cómo coger las funciones implementadas en los módulos y transformarlas en helpers de Twig.
