### ISSUE TITLE
[Causa de presión] Valorar opción de timeline vertical (tipo DDG) para los hitos

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#72]

**Comment by pr3ssh** [comment]
@poletika/managers Valorando ya la tercera opción, me decanto, sin duda alguna, por este [timeline](https://duckduckgo.com/about). Si lo véis bien me dispongo a intentar clonarlo. Creo que puede quedar bastante bien si lo conseguimos.

**Comment by AnaMariaCM** [comment]
Buenos días @pr3ssh . Me parece clara y visual esta línea temporal. Por mi, adelante con ello.
Me sigue faltando el poder linkar el contenido-título-2 líneas descriptivas de cada hito a un enlace, vídeo, noticia, etc. Sería genial que se pudiera hacer/incluir con esta timeline.
Pongo un ejemplo más que me pasó una compañera de Oxfam: http://www.simeimporta.org/ (Ir a plan de acción: veréis la timeline). Lo que me gusta de esto es que cuando tú te sitúas en un hito/circulito, clickas y te da mucha más info. Y también que igual de un vistazo abarca más período temporal (ves más hitos de una sola vez). Para todo lo demás, me quedo con tu ejemplo Pablo: sencillez, limpieza, claridad, visual... Mucho mejor. Vamos con ello. Si se puede incluir alguna de estas cuestiones (que se pueda linkar algo, o incluir un link, etc), fantastic. Gracias.
