### ISSUE TITLE
Generar API KEY de change.org

### ISSUE THREAD

**Issue by aleixx** [poletika/poletika.org#76]
Para una correcta integración de change.org en poletika sería necesario generar la API KEY y Secret en la propia plataforma change.

El proceso es el siguiente:

**1. Registrarse** (en caso de no estar) en [change.org](http://change.org)

![image](https://cloud.githubusercontent.com/assets/23332880/24674557/23cad55e-197c-11e7-9c64-99b370ce8699.png)

**2. Ir a la parte de desarrollador:** [Change developer](https://www.change.org/developers/api-key)

![image](https://cloud.githubusercontent.com/assets/23332880/24674595/49c48ed0-197c-11e7-9c22-d578da1f9bb4.png)

**3. Clickar en Show API Key**

![image](https://cloud.githubusercontent.com/assets/23332880/24674604/510b6cf4-197c-11e7-8b03-2ccadd01364a.png)

**4. Facilitarnos la información**:
- API KEY
- Secret

**Comment by AnaMariaCM** [comment]
Buenos días @aleixx @CIECODE 
API KEY: fa9cc5cf311da407c7d62827ec00475515e1f88244ae639805d11545f47403ed 
Secret: b4ff87af76a64cd7d27a3e4ff09e2369b806f7992851d86406a69f99e592921e 
@CIECODE He registrado a Polétika como perfil de Change. Espero que te parezca bien porque si registramos personas y luego estas personas cambiamos, es un poquito más de jaleo. Así que todo para Polétika. Buen día.

**Comment by pr3ssh** [comment]
@AnaMariaCM Genial.

@spolpen Puedes cambiar el API KEY en nuestra plataforma?

**Comment by spolpen** [comment]
@pr3ssh Actualizadas
