### ISSUE TITLE
Actualizar causa de presión fiscalidad: semana lucha paraísos fiscales

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#78]
Hola @spolpen @pr3ssh 

Necesitamos actualizar una de las causas de presión: la de fiscalidad.
Es la semana de lucha contra los paraísos fiscales y han pasado varias cosas esta semana que afectan a nuestra causa. Esto se mueve!! Y llega el momento de explorar con los hitos, internos, externos, y porcentajes: tenemos de todo.

1. Para la causa de presión, subir como píldoras de contenido los puntos 1.1., 1.2., y 1.3.: 
1.1. Lunes 3 de Abril 2017: Debate sobre los paraísos fiscales entre Congreso de los Diputados y Sociedad. La Plataforma por una Fiscalidad Justa debatió con los principales grupos parlamentarios qué hacer con los paraísos fiscales en esta legislatura. Organizaciones de la sociedad civil como Oxfam Intermón entregaron más de 100.000 firmas ciudadanas demandando mayor control y transparencia en la lucha contra el fraude y elusión fiscal: http://www.europapress.es/economia/energia-00341/noticia-sindicatos-asociaciones-exigen-sanciones-paraisos-fiscales-beneficiarios-20170403174705.html​ 
1.2. "Los impuestos son un buen indicador del estado de la democracia en un país", por Joaquín Estefanía http://economia.elpais.com/economia/2017/04/02/actualidad/1491145437_470067.html 
1.3. "3 de abril, Día contra los Paraísos Fiscales: ¿sabías que la inversión española en paraísos fiscales se ha multiplicado por 3 en el último año? En la semana mundial de acción contra los paraísos fiscales, sigue nuestras acciones y propuestas en #fueraparaísosfiscales"  https://www.youtube.com/watch?v=uAr4-AqkHKI
​​
**2. Para la causa de presión, crear un nuevo hito externo y otro interno**: 
2.1. Hito Externo: el 20 de febrero de 2017 el Pleno del Congreso de los Diputados aprueba la creación de una Subcomisión en el seno de la Comisión de Hacienda y Administraciones Públicas, sobre la armonización y coordinación fiscal europea e internacional y lucha contra el fraude fiscal y los paraísos fiscales.  Link al texto íntegro de la proposición aprobada: http://www.congreso.es/portal/page/portal/Congreso/PopUpCGI?CMD=VERLST&BASE=pu12&FMT=PUWTXDTS.fmt&DOCS=1-1&DOCORDER=LIFO&QUERY=%28BOCG-12-D-12.CODI.%29#(Página14) 
2.2. Hito interno: Jornada sobre Paraísos Fiscales en el Congreso de los Diputados - Plataforma por una Fiscalidad Justa, y entrega de firmas ciudadanas por Oxfam Intermón. Fecha: 3 de abril. ​
**2.3. % Logro: ok, a ver cómo ponemos esto.** La entrega de firmas/actoDebate en el Congreso del día 3 (hito interno) + el hito externo (la aprobación de la subcomisión) = nos acerca en un 25% a nuestro objetivo. 

**3. Para la temática fiscalidad, subir como píldora de contenido los puntos 3.1. y 3.2.**: 
3.1. Texto y link a vídeo: "3 de abril, Día contra los Paraísos Fiscales: ¿sabías que la inversión española en paraísos fiscales se ha multiplicado por 3 en el último año? En la semana mundial de acción contra los paraísos fiscales, sigue nuestras acciones y propuestas en #fueraparaísosfiscales"  https://www.youtube.com/watch?v=uAr4-AqkHKI
3.2. Tweet sb la concentración contra los paraísos fiscales en Madrid: https://twitter.com/inspiractionorg/status/848950804023304197

Cualquier duda, a vtra disposición. Esto 'no urge': durante lunes 10 o martes 11 de abril sería genial tenerlo, if possible. Gracias.

**Comment by pr3ssh** [comment]
@spolpen Lo metemos por ahora en DEV y en PRO por mantener entornos.

**Comment by spolpen** [comment]
Actualizado en ambos
