### ISSUE TITLE
Subir 2 píldoras de contenidos a causa de presión cooperación

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#79]
Hola @spolpen @pr3ssh Envié email viendo si pudierais subir estas 2 píldoras de contenidos a la causa de presión de cooperación antes de las 16h de hoy (lo siento!!!), dado que llevo una hora trasteando en la web y no soy capaz de publicarlas. Si entráis, quizá encontraréis las píldoras editadas (contenido definido, etc). Es solo publicarlas, que no lo consigo. 
¿Podréis hacerlo? Si no encontrárais los contenidos de las píldoras, me lo decís; pero esto yo sí lo encuentro. Lo que no soy capaz es de que salga al mundo exterior... Gracias!
Las píldoras se titulan "la Realidad de la Ayuda" y "PGE 2017: la AOD se estanca y se aleja de...".

**Comment by spolpen** [comment]
@AnaMariaCM Solucionado, te he indicado por correo el motivo igualmente.
