### ISSUE TITLE
Causa de presión 'Por un país que coopera: 0,24% ya!'. 

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#81]
@spolpen  EN LA PARTE CAUSAS DE PRESIÓN: 
- En Noticias - el link a Donor Tracker (03/02/17) dice que la página no puede ser encontrada. 
- ¿Se puede poner quién da las noticias en el título? Por ejemplo en "Es preciso que España cumpla su compromiso de revertir el declive de la ayuda al desarrollo" poner que es un artículo de la OCDE. 
- Noticia de 27 de abril - no se puede acceder directamente al link. 
- Evolución de la Hoja de Ruta - entiendo que no debe haber datos. es así? Le das al play y no pasa nada.

**Comment by spolpen** [comment]
@AnaMariaCM ¿Dónde debería ir el nombre de las noticias que indicas en el ejemplo de la OCDE?

**Comment by AnaMariaCM** [comment]
@spolpen al principio de la frase, tipo "OCDE: "ES preciso que España cumpla su compromiso de...". 
Gracias.

**Comment by AnaMariaCM** [comment]
Hola! Hemos visto que esto está hecho pero el issue no está cerrado.
Gracias. Lo cerramos @spolpen @pr3ssh @JuliaGaez @CIECODE
