### ISSUE TITLE
Título "últimas noticias" en varias páginas estáticas temáticas

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#86]
@spolpen En las páginas estáticas de Conflictos Internacionales / Protección social/Salarios Dignos/ Salarios Dignos, el título de la sección "últimas noticias" está pegado al primer cajón y en letra "Normal" (no sigue la misma tipografía que el resto de páginas estáticas).

**Comment by spolpen** [comment]
@AnaMariaCM ¿Puedes pasarme una captura con dos páginas donde te aparece con una fuente distinta? ¿Qué navegador usas?

**Comment by AnaMariaCM** [comment]
Hola @spolpen Pues era con Macbook Pro; tienes razón que yo uso ahora mi portátil y uso Chrome y me sale en todas igual. Pero ayer veía algunas diferentes. Si esto se ve como la imagen que adjunto, creo que el título de "Ultimas Noticias" debe destacar un poquito más: ser un poquito más grande, estar un poco más separado del cajón de la noticia-link siguiente, ir en negrita... En fin, ahí el diseño sabe más. Pero ahora mismo, tal y como lo veo así en la imagen adjunta, me parece que pierde relevancia y claridad. Gracias.
![image](https://user-images.githubusercontent.com/23697538/27367889-a36f5fae-564f-11e7-9238-a62ff61d5894.png)
