### ISSUE TITLE
Repositorio de páginas temáticas

### ISSUE THREAD

**Issue by AnaMariaCM** [poletika/poletika.org#90]
@spolpen Me pregunto: la idea del repositorio era tener una especie de 'carpeta-folder' por área temática donde la gente pudiera acceder fácilmente a 2-3-4 documentos clave de Polétika en esa temática. Ahora mismo solo hay 1 documento, y se ve/se puede acceder directamente. Sin embargo, ¿cómo aparecerá cuando haya más de un documento? SE verá en una lista hacia abajo? Cómo sabrá el usuario que hay varios docs clave? Gracias.

**Comment by spolpen** [comment]
@AnaMariaCM Sí, cuando se vayan subiendo más documentos aparecerán como en la siguiente captura de pantalla.
![repositorio](https://user-images.githubusercontent.com/9380577/27344788-d08df74c-55e7-11e7-82ed-a714e12bda99.png)

**Comment by AnaMariaCM** [comment]
ok, gracias!
