### ISSUE TITLE
Se muestra un error al dar de alta un hito (pero se crea correctamente)

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#97]
Cuando das de alta un hito se guarda pero se muestra un mensaje de Nginx de mantenimiento como si se hubiera producido un error 500 en el sistema. Creo que tiene que ver con el hook que se implementó.

**Comment by spolpen** [comment]
Como los hitos no tienen página propia ni se indica área o causa en ellos, se ha solucionado mostrando la página principal tras crearlos.
