### ISSUE TITLE
No se muestran correctamente las píldoras por temática

### ISSUE THREAD

**Issue by pr3ssh** [poletika/poletika.org#98]
Se ha dado un caso curioso. Un usuario de cooperación ha publicado píldoras en el área de salarios. Casualmente dichas píldoras aparecen, como deberían, en la sección de salarios pero por algún motivo aparecen también en cooperación.

Oxfam tiene más de una temática de edición pero eso creo que es un problema en el sistema por lo que se le crearán varios usuarios por cada temática.

Hay que revisar esa vista.

**Comment by spolpen** [comment]
Actualizada la vista
